[custom.all.indexed-graph]
type   = "local"
path   = "."
ipkg   = "indexed-graph.ipkg"
test   = "test/test.ipkg"

[custom.all.indexed-graph-generators]
type   = "local"
path   = "generators"
ipkg   = "indexed-graph-generators.ipkg"

[custom.all.indexed-graph-test]
type   = "local"
path   = "test"
ipkg   = "test.ipkg"

[custom.all.indexed-graph-profile]
type   = "local"
path   = "profile"
ipkg   = "indexed-graph-profile.ipkg"

[custom.all.ref1]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-ref1"
commit = "latest:lift1"
ipkg   = "ref1.ipkg"

[custom.all.array]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-array"
commit = "latest:lift1"
ipkg   = "array.ipkg"

[custom.all.containers]
type   = "git"
url    = "https://github.com/idris-community/idris2-containers"
commit = "latest:main"
ipkg   = "containers.ipkg"
