[custom.all.indexed-graph]
type   = "local"
path   = "."
ipkg   = "indexed-graph.ipkg"
test   = "test/test.ipkg"

[custom.all.indexed-graph-generators]
type   = "local"
path   = "generators"
ipkg   = "indexed-graph-generators.ipkg"

[custom.all.indexed-graph-test]
type   = "local"
path   = "test"
ipkg   = "test.ipkg"

[custom.all.indexed-graph-profile]
type   = "local"
path   = "profile"
ipkg   = "indexed-graph-profile.ipkg"

[custom.all.array]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-array"
commit = "latest:main"
ipkg   = "array.ipkg"

[custom.all.chem]
type   = "git"
url    = "git@github.zhaw.ch:hock/idris2-chem"
commit = "latest:main"
ipkg   = "chem.ipkg"
