---
name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{ github.repository }} with Idris2 latest
    runs-on: ubuntu-latest
    env:
      PACK_DIR: /root/.pack
    strategy:
      fail-fast: false
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install --yes nodejs
      - name: Build indexed-graph
        run: pack install indexed-graph
      - name: Test indexed-graph
        run: pack test indexed-graph -n 1000
      - name: Test indexed-graph on node
        run: pack --cg node test indexed-graph -n 1000
